### ISSUE TITLE
[Dribbblish]: Missing play button for tile entries

### ISSUE THREAD

**Issue by sansmoraxz** [spicetify/spicetify-themes#1037]
**Describe the bug**
Missing play icon for title entries on hover.

**To Reproduce**

```
spicetify config inject_css 1 replace_colors 1 overwrite_assets 1 inject_theme_js 1
spicetify config current_theme Dribbblish color_scheme base
```

Hover over any of the entry.

**Expected behavior**

Play icon missing. Should be something like this

![image](https://github.com/spicetify/spicetify-themes/assets/31374920/657686bf-65bd-4e95-aa25-26ed69452586)

**Screenshots**
![image](https://github.com/spicetify/spicetify-themes/assets/31374920/ee9660d1-e846-4c84-93d1-97376d06e892)

**Specifics (please complete the following information):**
 - OS: Windows 11
 - Spotify version: 1.2.31.1205
 - Spicetify version: 2.31.3

**Comment by sansmoraxz** [comment]
I have observed that injecting to `user.css` the following seems to fix it:

```css
.ButtonInner-medium-iconOnly {
    background-color: var(--background-base, #1ed760);
    color: var(--spice-text);
}
```

Not sure if it cascades the problem somewhere else.
