### ISSUE TITLE
[Ziro] Empty top bar obstructing cover art

### ISSUE THREAD

**Issue by Subsical** [spicetify/spicetify-themes#1118]
**Describe the bug**
There's a line (top bar) obstructing a good chunk of the cover art of any playlist or album I check.
I made sure that it was Ziro causing the issue by temporarily getting rid of every other extension, snippet or any general modification I've made. In the screenshot I've attached, I do have other extensions enabled, but I can assure you that the issue is not caused by any of them.

**To Reproduce**
1. Get the Ziro theme
2. Go to any playlist or album or anything with cover art
3. You should notice that a chunk of the image is being obstructed

**Expected behavior**
The top bar should only be present when it's necessary. Should be invisible when you're looking at a playlist or album.

**Screenshots**
![Spotify_v9yku3HfHB](https://github.com/user-attachments/assets/b9131677-c547-40a6-b535-4edc29ff4068)

**Logs**
![Spotify_fAl4Qu53OQ](https://github.com/user-attachments/assets/d37b7536-45fb-4094-b0fe-96ee8e07fd0e)

**Specifics**
 - OS: Windows
 - Spotify version: 1.2.45.454.gc16ec9f6
 - Spicetify version: 2.38.4
 - Theme: Ziro

**Comment by ItzzExcel** [comment]
I don't know if this code is well-written, but this worked for me.

```css
.main-topBar-container {
    position: relative;
}

.main-trackList-trackListHeader.main-trackList-trackListHeaderStuck, .marketplace-header {
    top: 0px !important;
}

/* Optional: fixes the border radius in top covers */
.main-entityHeader-container.main-entityHeader-withBackgroundImage
{
	border-radius: none !important
}
```

Proof:
![image](https://github.com/user-attachments/assets/644fb9e9-8892-4448-bf23-84b989b80a46)
![image](https://github.com/user-attachments/assets/d98b3082-3b41-4563-8415-895276e07465)
