### ISSUE TITLE
[Dribbblish] Add padding to the title on Artist page

### ISSUE THREAD

**Issue by Tamarindtype** [spicetify/spicetify-themes#1132]
**Question**
How to add a bottom padding on artist's name? I've tried to add it but didn't change.

And I noticed that my theme did not look the same as the Dribbblish preview images, is it because the latest version of the spotify client?

**Modified user.css**
```css
/* full screen artists background */
.main-entityHeader-container.main-entityHeader-withBackgroundImage,
.main-entityHeader-background,
.main-entityHeader-background.main-entityHeader-overlay:after {
    height: 100vh;
}

.artist-artistOverview-overview .main-entityHeader-withBackgroundImage h1 {
    font-size: 120px !important;
    line-height: 120px !important;
 ➡️ padding-bottom: 80px; ⬅️
}

.contentSpacing,
.artist-artistDiscography-headerContainer {
    padding-left: 64px;
    padding-right: 64px;
}

.artist-artistOverview-overview .main-entityHeader-headerText {
    justify-content: center;
}
``` 

**Expected behavior**
Increase the bottom padding on title.

**Screenshots**
![241206_17h40m40s_screenshot](https://github.com/user-attachments/assets/64342ebb-dea6-4308-b683-7ffccaf63e2f)
